apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sftpplus.workerName" . }}
  labels:
    app.kubernetes.io/name: sftpplus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sftpplus
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: worker
      annotations:
        checksum/initialization: {{ include "sftpplus.configChecksum" . }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: worker
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "/opt/sftpplus-initialization/worker-init.sh"]
          ports:
            - name: sftp
              containerPort: 10022
              protocol: TCP
            - name: https-files
              containerPort: 10443
              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: /opt/sftpplus-storage
            - name: initialization
              mountPath: /opt/sftpplus-initialization
              readOnly: true
            - name: worker-credentials
              mountPath: /opt/sftpplus-worker-credentials
              readOnly: true
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ required "storage.existingClaim is required" .Values.storage.existingClaim | quote }}
        - name: initialization
          configMap:
            name: {{ include "sftpplus.fullname" . }}-initialization
        - name: worker-credentials
          secret:
            secretName: {{ include "sftpplus.fullname" . }}-worker-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftpplus.workerName" . }}
  labels:
    app.kubernetes.io/name: sftpplus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
  ports:
    - name: sftp
      port: 10022
      targetPort: sftp
      protocol: TCP
    - name: https-files
      port: 10443
      targetPort: https-files
      protocol: TCP
