{{- $podLabels := include "sftpplus.podLabels" (dict "root" . "component" "worker") | fromYaml }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sftpplus.workerName" . }}
  labels:
    app.kubernetes.io/name: sftpplus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.workerDeployment.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ index $podLabels "app.kubernetes.io/instance" | quote }}
      app.kubernetes.io/component: {{ index $podLabels "app.kubernetes.io/component" | quote }}
  template:
    metadata:
      labels:
{{ toYaml $podLabels | indent 8 }}
      annotations:
{{ include "sftpplus.podAnnotations" (dict "root" . "component" "worker") | indent 8 }}
    spec:
{{- with .Values.workerDeployment.serviceAccountName }}
      serviceAccountName: {{ . | quote }}
{{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: worker
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "/opt/sftpplus-initialization/worker-init.sh"]
          ports:
            - name: sftp
              containerPort: 10022
              protocol: TCP
            - name: https-files
              containerPort: 10443
              protocol: TCP
{{- if .Values.workerService.httpFiles.enabled }}
            - name: http-files
              containerPort: {{ .Values.workerService.httpFiles.port }}
              protocol: TCP
{{- end }}
{{- if .Values.workerService.workerDebug.enabled }}
            - name: worker-debug
              containerPort: {{ .Values.workerService.workerDebug.port }}
              protocol: TCP
{{- end }}
          volumeMounts:
            - name: storage
              mountPath: /opt/sftpplus-storage
            - name: initialization
              mountPath: /opt/sftpplus-initialization
              readOnly: true
            - name: worker-credentials
              mountPath: /opt/sftpplus-worker-credentials
              readOnly: true
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "sftpplus.storageClaimName" . | quote }}
        - name: initialization
          configMap:
            name: {{ include "sftpplus.fullname" . }}-initialization
        - name: worker-credentials
          secret:
            secretName: {{ include "sftpplus.fullname" . }}-worker-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftpplus.workerName" . }}
  labels:
    app.kubernetes.io/name: sftpplus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
{{- with .Values.workerService.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.workerService.type }}
{{- with .Values.workerService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.workerService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
{{- end }}
  selector:
    app.kubernetes.io/instance: {{ index $podLabels "app.kubernetes.io/instance" | quote }}
    app.kubernetes.io/component: {{ index $podLabels "app.kubernetes.io/component" | quote }}
  ports:
    - name: sftp
      port: {{ .Values.workerService.sftpPort }}
{{- if and (eq .Values.workerService.type "NodePort") .Values.workerService.sftpNodePort }}
      nodePort: {{ .Values.workerService.sftpNodePort }}
{{- end }}
      targetPort: sftp
      protocol: TCP
    - name: https-files
      port: {{ .Values.workerService.httpsPort }}
{{- if and (eq .Values.workerService.type "NodePort") .Values.workerService.httpsNodePort }}
      nodePort: {{ .Values.workerService.httpsNodePort }}
{{- end }}
      targetPort: https-files
      protocol: TCP

{{- if .Values.workerService.httpFiles.enabled }}
    - name: http-files
      port: {{ .Values.workerService.httpFiles.port }}
      targetPort: http-files
      protocol: TCP
{{- end }}
{{- if .Values.workerService.workerDebug.enabled }}
    - name: worker-debug
      port: {{ .Values.workerService.workerDebug.servicePort }}
      targetPort: worker-debug
      protocol: TCP
{{- end }}
