[server]
uuid = worker-uuid
name = sftpplus-worker

[event-handlers/e137661a-150d-48f4-9239-4d9661492c11]
enabled = True
type = standard-stream
name = Standard Output Logger
output_format = logfmt
entry_content = {ts} {id} {component.name} {account.name} {account.peer.address} {account.peer.port} {message} {data_values}

[resources/DEFAULT-NODE-SYNC]
enabled = yes
type = node-sync
name = SFTPPlus cluster synchronization
role_in_cluster = node
sync_interval = 10
url = UPDATED_AT_RENDER_ADMIN_URL
tls_trusted_certificates = pin-public-key
pool_name = UPDATED_AT_RENDER_WORKER_POOL_NAME
node_name = UPDATED_AT_INIT_INSTANCE_NAME
password = UPDATED_AT_INIT_INSTANCE_PASSWORD
